name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build and Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rickyp00/charmander-front-end:latest

      - name: Push to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker login
            docker pull rickyp00/charmander-front-end:latest
            docker stop frontend_app
            docker rm frontend_app
            docker run --detach --rm -p 3000:3000 --name frontend_app rickyp00/charmander-front-end:latest
