module.exports = {
  exerciseList: {
    exercises: [
      {
        exercise_id: 1,
        exercise: 'DB Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 2,
        exercise: 'Hammer Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 3,
        exercise: 'Cable Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 4,
        exercise: 'Concentration Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 5,
        exercise: 'Preacher Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 6,
        exercise: 'DB Alternating Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 7,
        exercise: 'EZ Bar Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 8,
        exercise: 'Barbell Curls',
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        exercise_id: 9,
        exercise: 'Skullcrusher',
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        exercise_id: 10,
        exercise: 'DB Pull Overs',
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        exercise_id: 11,
        exercise: 'Tricep Pushdown',
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        exercise_id: 12,
        exercise: 'Dips',
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        exercise_id: 13,
        exercise: 'Preacher Curls',
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        exercise_id: 14,
        exercise: 'Tricep Kick Back',
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        exercise_id: 15,
        exercise: 'Closegrip Bench',
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        exercise_id: 16,
        exercise: 'DB Decline Press',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 17,
        exercise: 'Machine Incline Press',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 18,
        exercise: 'Cable Cross Overs',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 19,
        exercise: 'Barbell Bench Press',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 20,
        exercise: 'Machine Chest Press',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 21,
        exercise: 'DB Bench',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 22,
        exercise: 'Incline Bench',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 23,
        exercise: 'Decline Bench',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 24,
        exercise: 'Cambered Bar Bench',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 25,
        exercise: 'Machine Incline Bench',
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        exercise_id: 26,
        exercise: 'Shrugs',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 27,
        exercise: 'Upright Rows',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 28,
        exercise: 'DB Lateral Raise',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 29,
        exercise: 'DB Front Raises',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 30,
        exercise: 'DB Arnold Press',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 31,
        exercise: 'Machine Military Press',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 32,
        exercise: 'Push Press',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 33,
        exercise: 'Face Pulls',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 34,
        exercise: 'Cable Upright Rows',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 35,
        exercise: 'DB Cuban Press',
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        exercise_id: 36,
        exercise: 'Chest Supported Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 37,
        exercise: 'Inverted Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 38,
        exercise: 'DB Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 39,
        exercise: 'T-Bar Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 40,
        exercise: 'Lat Pulldowns',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 41,
        exercise: 'Seated Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 42,
        exercise: 'Seal Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 43,
        exercise: 'Bent-over Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 44,
        exercise: 'Rack Pulls',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 45,
        exercise: 'Pendlay Rows',
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        exercise_id: 46,
        exercise: 'DB RDLs',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 47,
        exercise: 'Seated Leg Curl',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 48,
        exercise: 'Hamstring Curls',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 49,
        exercise: 'Romanian Dealift',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 50,
        exercise: 'Good Mornings',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 51,
        exercise: 'Standing Leg Curl',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 52,
        exercise: 'Stiff Leg Deadlift',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 53,
        exercise: 'Single Leg Hip Thrust',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 54,
        exercise: 'Landmine Single Leg RDL',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 55,
        exercise: 'Reverse Hyperextension',
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        exercise_id: 56,
        exercise: 'Leg Extensions',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 57,
        exercise: 'Split Squat (Quad Emphasis)',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 58,
        exercise: 'Lunges',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 59,
        exercise: 'Reverse Hack Squat',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 60,
        exercise: 'Leg Press',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 61,
        exercise: 'Belt Squats',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 62,
        exercise: 'Goblet Squats',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 63,
        exercise: 'Front Squats',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 64,
        exercise: 'Barbell Squats',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 65,
        exercise: 'Safety Bar Squats',
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        exercise_id: 66,
        exercise: 'Barbell Glute Bridge',
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        exercise_id: 67,
        exercise: 'Split Squat (Glutes Emphasis)',
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        exercise_id: 68,
        exercise: 'Reverse Hyper',
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        exercise_id: 69,
        exercise: 'Glute Kickbacks',
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        exercise_id: 70,
        exercise: 'Smith Machine Hip Thrusts',
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        exercise_id: 71,
        exercise: 'Smith Machine Reverse Lunge',
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        exercise_id: 72,
        exercise: 'Lateral Lunge',
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        exercise_id: 73,
        exercise: 'Single Leg Calf Raise',
        muscle_group_id: 9,
        muscle_group: 'Calves',
      },
      {
        exercise_id: 74,
        exercise: 'Bent Knee Calf Raises',
        muscle_group_id: 9,
        muscle_group: 'Calves',
      },
      {
        exercise_id: 75,
        exercise: 'Calf Raises',
        muscle_group_id: 9,
        muscle_group: 'Calves',
      },
      {
        exercise_id: 76,
        exercise: 'Barbell Seated Calf Raise',
        muscle_group_id: 9,
        muscle_group: 'Calves',
      },
      {
        exercise_id: 77,
        exercise: 'Smith Machine Calf Raise',
        muscle_group_id: 9,
        muscle_group: 'Calves',
      },
      {
        exercise_id: 78,
        exercise: 'Seated Calf Raise',
        muscle_group_id: 9,
        muscle_group: 'Calves',
      },
      {
        exercise_id: 79,
        exercise: 'Barbell Russian Twists',
        muscle_group_id: 10,
        muscle_group: 'Abs',
      },
      {
        exercise_id: 80,
        exercise: 'Cable Crunch',
        muscle_group_id: 10,
        muscle_group: 'Abs',
      },
      {
        exercise_id: 81,
        exercise: 'Hanging Leg Raises',
        muscle_group_id: 10,
        muscle_group: 'Abs',
      },
      {
        exercise_id: 82,
        exercise: 'Weighted Situps',
        muscle_group_id: 10,
        muscle_group: 'Abs',
      },
      {
        exercise_id: 83,
        exercise: 'Front Plank',
        muscle_group_id: 10,
        muscle_group: 'Abs',
      },
    ],
    muscle_groups: [
      {
        muscle_group_id: 1,
        muscle_group: 'Biceps',
      },
      {
        muscle_group_id: 2,
        muscle_group: 'Triceps',
      },
      {
        muscle_group_id: 3,
        muscle_group: 'Chest',
      },
      {
        muscle_group_id: 4,
        muscle_group: 'Shoulders',
      },
      {
        muscle_group_id: 5,
        muscle_group: 'Back',
      },
      {
        muscle_group_id: 6,
        muscle_group: 'Hamstrings',
      },
      {
        muscle_group_id: 7,
        muscle_group: 'Quads',
      },
      {
        muscle_group_id: 8,
        muscle_group: 'Glutes',
      },
      {
        muscle_group_id: 9,
        muscle_group: 'Calves',
      },
      {
        muscle_group_id: 10,
        muscle_group: 'Abs',
      },
    ],
  },
};
